PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX sh: <http://www.w3.org/ns/shacl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  
 
ASK WHERE {  
  ?ValidationReport rdf:type sh:ValidationReport . 
  ?ValidationReport sh:conforms "false"^^xsd:boolean . 
  ?ValidationReport sh:ResultSeverity sh:Violation.
 } 
